// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drxjgrapfbqihnlyrdkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyeGpncmFwZmJxaWhubHlyZGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MjI2MjYsImV4cCI6MjA2NTA5ODYyNn0.LweSYHyYwfQ9n80s0ldEsO90_UoAiYsO9fRPzS1gDKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);